const CHARACTERS=[
{id:'gurych',name:'Гурыч',face:'🧓',role:'главком',bio:'Историк с треснутым стеклом, балаклавой с биткоином и левым боевым валенком.',skill:'История сама переписывается, когда он говорит «ага».',at:0},
{id:'britven',name:'Бритвень',face:'🦔',role:'молчаливый закон',bio:'Лысый ёж в татуировках. Ни слова. Кивок — высшая форма подписи.',skill:'Молча подтверждает один особенно странный план.',at:0},
{id:'kostyuk',name:'Костюк',face:'🎛️',role:'битмейкер',bio:'Звуковая партизанка. Её пульт слышно даже в Атлантиде.',skill:'Бит помогает найти нужный ритм в аномалии.',at:0},
{id:'mark',name:'Марк',face:'📹',role:'летописец',bio:'Снимает подвальные хроники и собирает Гуринголубя.',skill:'Находит детали, которые камера заметила раньше людей.',at:1},
{id:'maks',name:'Макс',face:'💻',role:'майнер',bio:'Три монитора, пять бирж, ноль доверия к прогнозу Рамм.',skill:'Может добыть GUR даже из выключенного сервера.',at:1},
{id:'sidorov',name:'Сидоров',face:'🛼',role:'следопыт',bio:'Ищет Колумба на роликах. Падает. Встаёт. Проверяет, не Колумб ли это.',skill:'Падение открывает путь, которого не было минуту назад.',at:2},
{id:'egor',name:'Егор',face:'🚙',role:'транспортный цех',bio:'Нива, светящиеся валенки и крик «УАААА!».',skill:'Доставляет экспедицию по маршрутам, не нанесённым на карту.',at:2},
{id:'pykhtych',name:'Пыхтыч',face:'💨',role:'дух вентиляции',bio:'Храпит в трубах. Иногда вылетает из них. Причину не знает даже он.',skill:'Чует скрытые переходы, если рядом достаточно дыма.',at:3},
{id:'slime',name:'Склизкий Жиж',face:'🫧',role:'оракул GUR',bio:'Живёт в бочке, булькает курс и принимает огрызки сникерсов.',skill:'Предупреждает о ресурсной ловушке. Обычно после неё.',at:3},
{id:'dymohlyup',name:'ДымОхлюп',face:'🌫️',role:'проводник',bio:'Почти жидкий туман. Шепчет и исчезает в другом дыму.',skill:'Проводит от любого густого тумана к Атлантиде.',at:3},
{id:'kartych',name:'Картыч',face:'🗺️',role:'архитектор маршрутов',bio:'Чертит карты в раздевалке между планом мира и ящиком изоленты.',skill:'Его стрелка работает даже тогда, когда коридор не существует.',at:2},
{id:'ramm',name:'Рамм',face:'🧮',role:'математика хаоса',bio:'Калькулятор дымится. Формально противник. Иногда танцует под бит.',skill:'Пересчитывает риск и неизменно ошибается в полезную сторону.',at:5},
{id:'bigmuk',name:'Бигмук',face:'🦔',role:'древняя сила',bio:'59-метровый Бритвень из Забытого подвала. Говорит «МУК...» и «БИИИГ...».',skill:'Один кивок меняет геометрию этажа.',at:4},
{id:'zavuch',name:'Завуч',face:'👁️‍🗨️',role:'сила природы',bio:'Всегда где-то в дыму. Не злая. Просто не видит.',skill:'Снимает системный поиск, пока все делают вид, что так и надо.',at:6},
{id:'hmurych',name:'Хмурыч',face:'🌑',role:'соседняя ветка',bio:'Гурыч из реальности, где пробирка в 00:59 осталась закрытой.',skill:'Знает, какой выбор ты ещё не сделал.',at:7}
];
const LOCATIONS=[
{id:'basement',name:'Подвал №59',short:'ГЛАВНЫЙ ПОДВАЛ',icon:'🕯️',code:'B-0059',chapter:'01 / ПРОБУЖДЕНИЕ',coords:'X:59 · Y:4:20',desc:'Сервер школы ловит частоту, которой нет в журнале оборудования. Под столом — валенок. Рядом — следы, похожие на карту.',objective:'Запусти сервер и собери первый состав парада.',scene:'Четыре двадцать. Не по часам — по ощущению. Гурыч кладёт ладонь на старый сервер, и красные диоды отвечают зелёными. В динамиках слышен бит Костюк, хотя пульт выключен.\n\n— Ага... Значит, оно опять, — говорит Гурыч.\n\nБритвень стоит у двери «НЕ ВХОДИТЬ». Он молчит так убедительно, что дверь сама закрывается.',dialogue:'МАРК: Камера пишет помехи, хотя батарея снята.\nМАКС: Если сервер майнит — помехи окупаются.\nБРИТВЕНЬ: (кивает на валенок)',choices:[
{title:'Врубить бит Костюк',hint:'Синхронизировать сервер с частотой подвала.',cost:'БЕСПЛАТНО',fx:{trust:13,heat:4,smoke:4,gur:12},result:'Первый удар проходит сквозь бетон. Сервер отвечает басом. Бритвень кивает один раз — значит, экспедиция официально существует.',tag:'РИТМ'},
{title:'Доверить запуск Бритвеню',hint:'Попросить молчаливый закон подтвердить схему.',cost:'−1 СНИКЕРС',fx:{snickers:-1,trust:18,heat:-4,smoke:0,gur:4},result:'Бритвень смотрит на два кабеля, потом на тебя. Он выбирает третий, которого раньше не было. Сервер запускается. Кивок принят.',tag:'КИВОК'},
{title:'Поручить запуск Максу',hint:'Проверить, не прячется ли GUR в старом диске.',cost:'БЕСПЛАТНО',fx:{gur:34,trust:4,heat:9,smoke:0},result:'Макс нашёл кошелёк на диске 2007 года. Баланс — 34 GUR. Пароль «password59» уже сменён на «password60».',tag:'МАЙНИНГ'}]},
{id:'vent',name:'Вентиляция',short:'СЕТЬ ПЫХТЫЧА',icon:'〰️',code:'AIR-0420',chapter:'02 / СВЯЗУЮЩАЯ СЕТЬ',coords:'X:труба · Y:хррр',desc:'Трубы соединяют подвалы, крышу и места, которых план БТИ не признаёт. Внутри пахнет пылью и свежим сникерсом.',objective:'Расшифруй маршрут Гуринголубя.',scene:'Решётка отходит сама. Изнутри раздаётся храп, точно попадающий в тональность Костюк. В дыму мелькает кибернетическое крыло: Гуринголубь несёт крипто-флешку.',dialogue:'ПЫХТЫЧ: Хррр... (не открывая глаз)\nМАРК: На флешке три файла. Все называются «финал_точно_последний_7».\nКАРТЫЧ: Труба налево ведёт направо. Я проверял.',choices:[
{title:'Следовать за Гуринголубем',hint:'Пусть Марк расшифрует запись по кадрам.',cost:'БЕСПЛАТНО',fx:{trust:9,heat:8,smoke:8,gur:14},result:'На записи сначала пустой коридор, затем тот же коридор, но на 59 лет старше. В последнем кадре — крыша. Птица курлычет басом.',tag:'СИГНАЛ'},
{title:'Разбудить Пыхтыча битом',hint:'Проверить, может ли храп открыть дальний шлюз.',cost:'БЕСПЛАТНО',fx:{trust:8,heat:-3,smoke:17,gur:4},result:'Пыхтыч просыпается на полтакта, выдыхает клуб дыма и снова засыпает. В клубе — схема крыши. Никто не спрашивает, откуда.',tag:'ХРРР'},
{title:'Заклеить переход изолентой',hint:'Надёжный маршрут, если Картыч не перевернул карту.',cost:'−18 GUR',fx:{gur:-18,trust:7,heat:-2,tape:-1},result:'Изолента держит стену, стену держит коридор, коридор держит слово Картыча. Труба приводит к крыше. Почти напрямую.',tag:'РЕМОНТ'}]},
{id:'roof',name:'Крыша школы',short:'ГНЕЗДО ГОЛУБЯ',icon:'🕊️',code:'RF-3115',chapter:'03 / ВЫСОКАЯ ЧАСТОТА',coords:'X:над школой · Y:куда-то',desc:'На крыше Марк ставит ретранслятор, а Сидоров ищет Колумба среди антенн. Ветер дует из вентиляции.',objective:'Найди след Колумба и передай сигнал дальше.',scene:'Сидоров вылетает из-за трубы, делает короткий кульбит и приземляется на колено.\n\n— Я упал не потому, что поскользнулся. Я проверял, есть ли здесь гравитация. Есть. Колумба пока нет.\n\nГуринголубь садится на антенну и выкладывает карту, сложенную в форме валенка.',dialogue:'СИДОРОВ: След Колумба свежий. Ему лет примерно пятьсот.\nМАРК: Ретранслятор готов. Нужен источник питания.\nЕГОР: У меня есть провода. И Нива. Выбирайте.',choices:[
{title:'Помочь Сидорову с поисками',hint:'Каждое падение становится новой отметкой карты.',cost:'−1 СНИКЕРС',fx:{snickers:-1,trust:12,heat:1,gur:8},result:'Под антеннами обнаружен глобус. На нём материки и маленькая подпись «Колумб здесь был, но ушёл за шоколадкой». Ретранслятор ловит Атлантиду.',tag:'СЛЕД'},
{title:'Запустить видео Марка в сеть',hint:'Виральный сигнал может перешагнуть границу миров.',cost:'БЕСПЛАТНО',fx:{gur:28,trust:6,heat:12,smoke:3},result:'Ролик набирает 3115 просмотров за 59 секунд. На 3116-м кадре в окне появляется берег. Марк утверждает, что монтажа не было. Камера — тоже.',tag:'ЭФИР'},
{title:'Подключить батарею Нивы Егора',hint:'Энергии хватит. Возможно, хватит и на старт.',cost:'БЕСПЛАТНО',fx:{trust:9,heat:3,smoke:4,gur:6},result:'Нива заводится, хотя ключ остался внизу. Светящиеся валенки Егора загораются в такт сигналу. На экране Макса возникает координата: третья дверь слева.',tag:'УАААА'}]},

{id:'forgotten',name:'Забытый подвал',short:'ЛОГОВО БИГМУКА',icon:'🦔',code:'B-0059-OLD',chapter:'04 / ТРЕТЬЯ ДВЕРЬ',coords:'X:бойлер · Y:слева',desc:'Третья дверь слева, если свернуть у бойлера. За ней спит существо, которому лестница явно мала.',objective:'Разбуди Бигмука и добудь фрагмент Атлантиды.',scene:'Пол покрыт пылью, похожей на звёздную карту. В центре — Бритвень размером с пятиэтажку. Он спит, свернувшись вокруг старого школьного глобуса.\n\nГурыч снимает очки.\n— Не будить резко. Он и так почти проснулся.\n\nБигмук открывает один глаз. Земля дрожит в радиусе 59 километров, но только в таблице Рамм.',dialogue:'БИГМУК: МУК...\nБРИТВЕНЬ: (кивает)\nРАММ: Радиус дрожания — 58,9 км. Я всё посчитала!\nГУРЫЧ: Ага...',choices:[
{title:'Войти с ответным кивком',hint:'Старый закон узнаёт новый. Без резких движений.',cost:'БЕСПЛАТНО',fx:{trust:18,heat:-5,smoke:6,gur:9},result:'Бигмук закрывает глаз и кивает во сне. Из глобуса выпадает осколок карты. Никто не понял, как глобус пережил кивок.',tag:'ЗАКОН'},
{title:'Дать Костюк сыграть низкий бит',hint:'Найти частоту, на которой спит гигант.',cost:'БЕСПЛАТНО',fx:{trust:11,heat:5,smoke:14,gur:12},result:'Бигмук затверкал. Пыль поднялась спиралью и сложилась в карту. Картыч замечает, что вход теперь находится внутри выхода.',tag:'РЕЗОНАНС'},
{title:'Оставить сникерс у двери',hint:'Запас — универсальный язык, даже для 59 метров.',cost:'−1 СНИКЕРС',fx:{snickers:-1,trust:10,heat:-2,gur:18},result:'Сникерс исчезает в складке пространства. Слышится довольное «БИИИГ...». На его месте лежит пачка изоленты.',tag:'ПОДАРОК'}]},
{id:'ramm',name:'Подвал Рамм',short:'ЗОНА СКУКИ',icon:'🧮',code:'CALC-ERROR',chapter:'05 / ВОЙНА ФОРМУЛ',coords:'X=неверно · Y=почти',desc:'Здесь всегда светло, сухо и можно прочитать каждую инструкцию. Именно поэтому сюда никто не хочет заходить.',objective:'Сломай алгоритм Рамм, не сломав саму Рамм.',scene:'Рамм окружила сервер калькуляторами. На доске: «ПЫЩ = дым × валенок² / скука». Рядом мелом добавлено: «проверить единицы измерения».\n\n— Я всё посчитала! — объявляет Рамм.\n\nГлавный калькулятор показывает «3115». Она нажимает равно. На дисплее появляется «АГА».',dialogue:'РАММ: Гурыч, у вас дым не по ГОСТу.\nГУРЫЧ: А по какому?\nРАММ: Сейчас посчитаю.\nКАЛЬКУЛЯТОР: (начинает дымиться)',choices:[
{title:'Пересчитать бит Костюк вместе',hint:'Математика встречает ритм. Рамм получает новую переменную.',cost:'БЕСПЛАТНО',fx:{trust:17,heat:2,smoke:5,gur:14},result:'Рамм насчитала 3,7 такта. Это неверно, но все попали в ритм. Она оставляет калькулятор в команде — он уже знает припев.',tag:'СОЮЗ'},
{title:'Показать прогноз Склизкого Жижа',hint:'Проверить курс на независимом бульканье.',cost:'+1 СНИКЕРС',fx:{snickers:1,trust:8,heat:-2,gur:22},result:'Жиж предсказывает рост, падение и бочку. Рамм строит график. График получается похож на ежика. Бритвень одобряет кивком.',tag:'ПРОГНОЗ'},
{title:'Напустить дыма по периметру',hint:'Классический способ скрыть непредусмотренную переменную.',cost:'−1 ИЗОЛЕНТА',fx:{tape:-1,trust:9,heat:-14,smoke:22},result:'Завуч проходит мимо двери, останавливается и продолжает путь. Рамм сохраняет формулу в дыму — файл нельзя открыть без валенка.',tag:'ЗАВУЧ В ДЫМУ'}]},
{id:'atlantis',name:'Атлантида',short:'ЗА КАРТОЙ',icon:'🌊',code:'ATL-∞',chapter:'06 / ГУРИНТАЙМ',coords:'X:карман · Y:между',desc:'Мифическая страна рядом со сникерсом в кармане Гурыча. Здесь валенки не тонут и у Рамм заканчиваются числа.',objective:'Реши, кому принадлежит дорога в Атлантиду.',scene:'Вода тёмная и спокойная. Под поверхностью виден знакомый школьный подвал, только окна смотрят в космос. ДымОхлюп шепчет, что Атлантида — не пункт назначения. Это место, где все пути помнят, откуда начались.\n\nГурыч достаёт последний фрагмент карты. Бритвень кивает. Даже Рамм пока ничего не считает.',dialogue:'ДЫМОХЛЮП: Тут все двери ведут домой.\nКАРТЫЧ: Дом — это направление или координата?\nРАММ: Не знаю. И это хороший знак.\nГУРЫЧ: ПЫЩ.',choices:[
{title:'Открыть Атлантиду всем',hint:'Передать карту Гуринголубю. Пусть каждый найдёт свой путь.',cost:'БЕСПЛАТНО',fx:{trust:24,heat:8,smoke:25,gur:30},result:'Атлантида раскрывается. Бритвень кивает. Марк нажимает Loop, Костюк добавляет новый бит, а Гурыч оставляет в дыму дорогу назад. ПЫЩ-парад переходит в следующую фазу.',tag:'ОТКРЫТЫЙ ФИНАЛ'},
{title:'Оставить вход в кармане Гурыча',hint:'Сохранить Атлантиду как запасной выход.',cost:'−1 СНИКЕРС',fx:{snickers:-1,trust:16,heat:-8,gur:55},result:'Атлантида складывается до размера кармана. Рамм записывает это как «геометрия одежды». Валенок продолжает лететь дальше.',tag:'ТИХИЙ ФИНАЛ'},
{title:'Позвать Рамм считать волны',hint:'Пригласить формулы в неизвестность.',cost:'БЕСПЛАТНО',fx:{trust:30,heat:3,smoke:10,gur:20},result:'Рамм считает до третьей волны, сбивается и смеётся. Впервые не пытается начать сначала. Новая фаза называется «пока не знаем — идём».',tag:'НЕВЕРОЯТНЫЙ СОЮЗ'}]},
{id:'hmurych',name:'Подвал Хмурыча',short:'ПОНЕДЕЛЬНИК',icon:'🌑',code:'00:59-ALT',chapter:'07 / ПАРАЛЛЕЛЬНАЯ ВЕТКА',coords:'X:понедельник · Y:не выпил',desc:'Другой подвал. Серый свет. Другой Гурыч. Он однажды не выпил пробирку в 00:59.',objective:'Узнай, что происходит с историей, если не сказать «ПЫЩ».',scene:'Дверь открывается только по понедельникам — хотя сейчас четверг. За ней Хмурыч: тот же Гурыч, но тише, серее и вместо «ПЫЩ» говорит «пщ».\n\n— Ты пришёл из ветки, где валенок летит? — спрашивает он.\n\nЗа его спиной всё по правилам. Даже дым стоит по линейке.',dialogue:'ХМУРЫЧ: Здесь спокойно.\nГУРЫЧ: И как тебе?\nХМУРЫЧ: Пщ.\nБРИТВЕНЬ: (не кивает)',choices:[
{title:'Показать ему бит Костюк',hint:'Дать параллельной ветке один звук свободы.',cost:'БЕСПЛАТНО',fx:{trust:20,heat:0,smoke:5,gur:0},result:'Хмурыч слушает. Уголок его рта поднимается на миллиметр. «Пщ» звучит почти как «ПЫЩ». Ветка остаётся отдельной, но дверь больше не заперта.',tag:'ДРУГАЯ ВЕТКА'},
{title:'Оставить ему боевой валенок',hint:'Знак, что история может выбрать другой путь.',cost:'−1 СНИКЕРС',fx:{snickers:-1,trust:15,heat:-5,smoke:8,gur:0},result:'Хмурыч берёт валенок. В его подвале впервые появляется сквозняк. Он кивает. Бритвень не кивает. Это почти исторический момент.',tag:'ПАРАДОКС'},
{title:'Спросить о 00:59',hint:'Разобрать точку, в которой разошлись две версии.',cost:'−10 GUR',fx:{gur:-10,trust:8,heat:0,smoke:0},result:'Хмурыч рассказывает о закрытой пробирке и открытом понедельнике. В журнале появляется новая запись: иногда неиспользованная возможность — тоже дверь.',tag:'СЕКРЕТ'}]}
];
const ARTIFACTS=[{id:'valenok',name:'Боевой валенок',icon:'🥾',desc:'Левый, стоптанный. Открывает путь ударом о глобус.',count:1},{id:'tape',name:'Изолента',icon:'🟨',desc:'Чинит вещи, стены и некоторые причинно-следственные связи.',count:3},{id:'map',name:'Карта Картыча',icon:'🗺️',desc:'Свернута не той стороной. Это, кажется, правильно.',count:1},{id:'pigeon',name:'Крипто-флешка',icon:'🕊️',desc:'Гуринголубь доставил архивный пакет.',count:0},{id:'knowledge',name:'Косяк знаний',icon:'📜',desc:'Учебник истории. После трёх затяжек видна Атлантида.',count:1},{id:'snickers',name:'Сникерсы',icon:'🍫',desc:'Резерв энергии. Не выходить из подвала без запаса.',dynamic:true}];

const ORDER=['basement','vent','roof','forgotten','ramm','atlantis'];
const SAVE_KEY='pyshparad-3115-v4';
const DEFAULT_STATE={gur:120,snickers:3,trust:12,heat:8,smoke:12,tape:3,unlocked:['basement'],done:[],chosen:{},crew:['gurych','britven','kostyuk'],puffs:0,secret:false,oddity:0,quests:{snickers:false,pigeon:false,ramm:false},achievements:[],log:[],view:'expedition',codex:'welcome',sound:false,loops:0};
function freshState(){return JSON.parse(JSON.stringify(DEFAULT_STATE))}
function loadState(){try{const s=JSON.parse(localStorage.getItem(SAVE_KEY));return s&&typeof s==='object'?Object.assign(freshState(),s):freshState()}catch{return freshState()}}
let state=loadState(),selected='basement',toastTimer,smokeCooldown=false,oddityQuotes=0,secretSeen=0;
const $=q=>document.querySelector(q),$$=q=>Array.from(document.querySelectorAll(q));
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));$('#saveStatus').textContent='АВТОСОХРАНЕНО';$('#footerSave').textContent='ЛОКАЛЬНАЯ ХРОНИКА · АВТОСЕЙВ'}catch{$('#saveStatus').textContent='ХРАНИЛИЩЕ НЕДОСТУПНО'}}
function safe(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(message){const box=$('#toast');box.textContent=message;box.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.classList.remove('show'),2700)}
function log(actor,message,time){state.log.unshift({actor:actor,message:message,time:time||clockStamp()});state.log=state.log.slice(0,40)}
function clockStamp(){let h=new Date().getHours(),m=new Date().getMinutes();return String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')}
function setMeter(id,value,max){const el=$(id);if(el)el.style.width=Math.max(0,Math.min(100,value/max*100))+'%'}
function activeLocation(){return LOCATIONS.find(x=>x.id===selected)||LOCATIONS[0]}
function noticeUnlocks(){const cleared=state.done.length;CHARACTERS.forEach(c=>{if(c.id==='hmurych')return;if(c.at<=cleared&&!state.roster?.includes(c.id)){state.roster=state.roster||[];state.roster.push(c.id);log('АРХИВ','Новый сигнал личности: '+c.name+'.')}})}
function unlockedCharacters(){const roster=state.roster||['gurych','britven','kostyuk'];return CHARACTERS.filter(c=>roster.includes(c.id))}
function checkAchievements(){const tests=[['first_puff',state.puffs>=1,'Первый ПЫЩ','Вентиляция присвоила тебе имя.'],['smoke_3',state.puffs>=3,'Дымовой коридор','Открыта ветка Хмурыча.'],['first_case',state.done.length>=1,'Дело заведено','Бритвень кивнул — формально.'],['six_cases',state.done.length>=6,'Шесть из шести','Атлантида нанесена на карту.'],['secret_code',state.secret,'Пароль принят','Секретный архив теперь доступен.'],['crew_8',unlockedCharacters().length>=8,'Большой сбор','Подвалу не хватает складных стульев.']];for(const [id,yes,title,text] of tests)if(yes&&!state.achievements.includes(id)){state.achievements.push(id);log('ДОСТИЖЕНИЕ',title+' — '+text);toast('ДОСТИЖЕНИЕ: '+title)}}
function renderResources(){$('#gur').textContent=state.gur;$('#snickers').textContent=state.snickers;$('#trust').innerHTML=state.trust+'<span>/100</span>';$('#heat').innerHTML=state.heat+'<span>%</span>';$('#heatHint').textContent=state.heat>75?'СИСТЕМА УЖЕ ИЩЕТ ПОДВАЛ':'пока можно пройти незамеченным';$('#heatMeter').style.width=state.heat+'%';$('#gurMeter').style.width=Math.min(100,state.gur/240*100)+'%';$('#snickersMeter').style.width=Math.min(100,state.snickers/6*100)+'%';$('#trustMeter').style.width=state.trust+'%';$('#smokeValue').textContent=state.smoke+'%';$('#smokeMeter').style.width=state.smoke+'%';$('.warning').classList.toggle('hot',state.heat>70);$('#crewCount').textContent=unlockedCharacters().length;$('#itemCount').textContent=state.snickers+state.tape+3}
function renderMap(){const host=$('#mapNodes');host.innerHTML='';const points=LOCATIONS;points.forEach((loc,i)=>{let open=state.unlocked.includes(loc.id)||(loc.id==='hmurych'&&state.secret),done=state.done.includes(loc.id),b=document.createElement('button');b.className='map-node'+(open?'':' locked')+(done?' cleared':'')+(selected===loc.id?' selected':'')+(loc.id==='hmurych'&&open?' revealed':'');b.dataset.node=loc.id;b.disabled=!open;b.style.left='';b.innerHTML='<span class="node-icon">'+loc.icon+'</span><span class="node-name">'+safe(loc.name)+'</span><span class="node-sub">'+safe(loc.short||loc.code)+'</span><span class="node-state">'+(done?'✓':open?'●':'⌑')+'</span>';if(loc.id==='basement'){b.style.left='14%';b.style.top='77%'}if(loc.id==='vent'){b.style.left='41%';b.style.top='53%'}if(loc.id==='roof'){b.style.left='70%';b.style.top='75%'}if(loc.id==='forgotten'){b.style.left='48%';b.style.top='18%'}if(loc.id==='ramm'){b.style.left='72%';b.style.top='29%'}if(loc.id==='atlantis'){b.style.left='16%';b.style.top='27%'}if(loc.id==='hmurych'){b.style.left='87%';b.style.top='53%';if(open)b.classList.add('revealed')}b.onclick=()=>selectLocation(loc.id);host.appendChild(b)});$('#mapHint').onclick=()=>mapHint()}
function selectLocation(id){if(id==='hmurych'&&!state.secret)return toast('СИГНАЛ В ТУМАНЕ. НУЖНО БОЛЬШЕ ПЫЩ.');if(!state.unlocked.includes(id)&&id!=='hmurych')return toast('МАРШРУТ ЗАКРЫТ. КАРТЫЧ ЕЩЁ НЕ ДОРИСОВАЛ.');selected=id;renderSelected();renderMap();if(innerWidth<680)$('#missionTitle').scrollIntoView({behavior:'smooth',block:'center'})}
function renderSelected(){const loc=LOCATIONS.find(x=>x.id===selected)||(state.secret?LOCATIONS.find(x=>x.id==='hmurych'):LOCATIONS[0]);$('#missionChapter').textContent=loc.chapter;$('#missionTitle').textContent=loc.name;$('#missionArt').querySelector('#missionEmoji').textContent=loc.icon;$('#artCode').textContent=loc.code;$('#missionDescription').textContent=loc.desc;$('#missionObjective').textContent=state.done.includes(loc.id)?'Дело уже записано. Можно вернуться и проверить другой ход.':loc.objective;$('#launchMission').textContent=state.done.includes(loc.id)?'ПЕРЕИГРАТЬ ЭПИЗОД ↻':'НАЧАТЬ ЭПИЗОД →';$('#launchMission').onclick=()=>startMission(loc);renderActiveCrew()}
function renderActiveCrew(){$('#activeCrew').innerHTML=state.crew.map(id=>{const c=CHARACTERS.find(x=>x.id===id);return c?'<span class="active-face" title="'+safe(c.name)+' · '+safe(c.role)+'">'+c.face+'</span>':''}).join('')+'<button class="active-face empty-face" data-goto-crew="1">+</button>';$('#activeCrew [data-goto-crew]').onclick=()=>switchView('crew')}
function renderJournal(){$('#journal').innerHTML=state.log.slice(0,9).map(x=>'<div class="journal-line"><time>'+safe(x.time)+'</time><b>'+safe(x.actor)+'</b><em>'+safe(x.message)+'</em></div>').join('')||'<div class="journal-line"><time>04:20</time><b>СИСТЕМА</b><em>Подвал ответил на частоту 3115.</em></div>'}
function renderCrew(){const available=unlockedCharacters();$('#crewCounter').textContent=state.crew.length+' / 4 В ПОЛЕ · '+available.length+' ДОСТУПНО';$('#crewGrid').innerHTML=CHARACTERS.map(c=>{let open=available.some(x=>x.id===c.id),selected=state.crew.includes(c.id);return '<article class="character '+(!open?'locked':'')+' '+(selected?'selected':'')+'"><div class="character-top"><span class="character-portrait">'+(open?c.face:'🔒')+'</span><span class="char-status">'+(selected?'● В ПОЛЕ':open?'ДОСТУПЕН':'СИГНАЛ ЗАКРЫТ')+'</span></div><h3>'+safe(c.name)+'</h3><span class="role">'+safe(c.role)+'</span><p>'+safe(c.bio)+'</p><div class="character-foot"><span>'+safe(c.skill)+'</span>'+(open?'<button data-crew="'+c.id+'">'+(selected?'СНЯТЬ':'ВЗЯТЬ')+'</button>':'')+'</div></article>'}).join('');$$('[data-crew]').forEach(b=>b.onclick=()=>toggleCrew(b.dataset.crew))}
function toggleCrew(id){if(state.crew.includes(id)){if(state.crew.length===1)return toast('Нужен хотя бы один участник. Гурыч не умеет клонироваться.');state.crew=state.crew.filter(x=>x!==id);toast('Участник вернулся в штаб.')}else{if(state.crew.length>=4)return toast('Четыре места. Пятый может ехать на крыше Нивы.');state.crew.push(id);toast(CHARACTERS.find(c=>c.id===id).name+' в составе.')}renderCrew();renderSelected();save()}
function switchView(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+view));$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.mobile-nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));state.view=view;if(view==='crew')renderCrew();if(view==='inventory')renderInventory();if(view==='codex')renderCodex();save();window.scrollTo({top:0,behavior:'smooth'})}

function makeLogModal(kicker,title,body,buttons){$('#modalKicker').textContent=kicker;$('#modalTitle').textContent=title;$('#modalContent').innerHTML=body;$('#modalChoices').innerHTML='';$('#modalFooter').innerHTML='';(buttons||[]).forEach(b=>{let el=document.createElement('button');el.className='btn '+(b.primary?'btn-primary':'');el.textContent=b.label;el.onclick=b.onClick;$('#modalFooter').appendChild(el)});$('#modalBackdrop').classList.add('open');$('#modalClose').focus()}
function closeModal(){$('#modalBackdrop').classList.remove('open')}
function startMission(loc){if(state.heat>=98&&state.smoke<30){makeLogModal('СИСТЕМНОЕ ПРЕДУПРЕЖДЕНИЕ','Поиск почти завершён','<p>Система засекла активный маршрут. Подними уровень дыма кнопкой <b>ПЫЩ</b>, чтобы сбить поиск, или подожди в штабе.</p>',[{label:'ПЫЩ!',primary:true,onClick:()=>{closeModal();launchPysh()}},{label:'Остаться в штабе',onClick:closeModal}]);return}
const replay=state.done.includes(loc.id);const scene='<div class="scene-illustration">'+safe(loc.code)+' &nbsp; / &nbsp; '+safe(loc.coords)+'<br><br>'+safe(loc.objective)+'</div><p>'+safe(loc.scene).replace(/\n/g,'<br>')+'</p><div class="dialogue">'+safe(loc.dialogue).replace(/\n/g,'<br>')+'</div><p class="fine-print">'+(replay?'Повторный проход: архив уже записан. Вариант решения останется в летописи.':'Первое прохождение откроет следующую отметку карты.')+'</p>';
$('#modalKicker').textContent=loc.chapter;$('#modalTitle').textContent=loc.name;$('#modalContent').innerHTML=scene;$('#modalChoices').innerHTML=loc.choices.map((c,i)=>'<button class="choice" data-choice="'+i+'"><span><b>'+safe(c.title)+'</b><small>'+safe(c.hint)+'<br>'+safe(c.tag)+'</small></span><span class="choice-cost">'+safe(c.cost)+'</span></button>').join('');$('#modalFooter').innerHTML='<span class="fine-print">В СОСТАВЕ: '+state.crew.map(id=>CHARACTERS.find(c=>c.id===id)?.name).filter(Boolean).join(' · ')+'</span>';$$('[data-choice]').forEach(b=>b.onclick=()=>resolveChoice(loc,+b.dataset.choice));$('#modalBackdrop').classList.add('open')}
function crewBonus(loc,fx){let bonus={};if(state.crew.includes('kartych'))bonus.heat=-2;if(loc.id==='roof'&&state.crew.includes('mark'))bonus.gur=(bonus.gur||0)+5;if(loc.id==='vent'&&state.crew.includes('pykhtych'))bonus.smoke=(bonus.smoke||0)+5;if(loc.id==='ramm'&&state.crew.includes('ramm')){bonus.trust=(bonus.trust||0)+3;bonus.gur=(bonus.gur||0)+4}if(loc.id==='forgotten'&&state.crew.includes('britven'))bonus.trust=(bonus.trust||0)+2;return bonus}
function resolveChoice(loc,index){const choice=loc.choices[index],fx=Object.assign({},choice.fx),wasDone=state.done.includes(loc.id);const bonus=crewBonus(loc,fx);Object.keys(bonus).forEach(k=>fx[k]=(fx[k]||0)+bonus[k]);if((state.gur+(fx.gur||0))<0)return toast('НЕДОСТАТОЧНО GUR. Макс предлагает не паниковать.');if((state.snickers+(fx.snickers||0))<0)return toast('СНИКЕРСОВ НЕТ. Бритвень смотрит на карман.');if((state.tape+(fx.tape||0))<0)return toast('ИЗОЛЕНТА ЗАКОНЧИЛАСЬ. Это тревожный сигнал.');['gur','snickers','trust','heat','smoke','tape'].forEach(k=>{if(fx[k])state[k]=Math.max(0,Math.min(k==='gur'?999:k==='trust'||k==='heat'||k==='smoke'?100:99,state[k]+fx[k]))});
if(state.smoke>65){state.heat=Math.max(0,state.heat-5);state.smoke=Math.max(0,state.smoke-7);log('ЗАВУЧ','Прошла рядом. Не заметила ничего.')}
if(!wasDone){state.done.push(loc.id);if(ORDER.includes(loc.id)){let i=ORDER.indexOf(loc.id),next=ORDER[i+1];if(next&&!state.unlocked.includes(next)){state.unlocked.push(next);log('КАРТЫЧ','Открылся маршрут: '+LOCATIONS.find(x=>x.id===next).name+'.')}}noticeUnlocks();if(loc.id==='roof')state.quests.pigeon=true;if(loc.id==='ramm')state.quests.ramm=true;if(loc.id==='vent')state.quests.snickers=state.snickers>0}
state.chosen[loc.id]=index;state.heat=Math.min(100,state.heat+7);state.loops++;log(loc.name,choice.result);if(loc.id==='atlantis'){state.ending=true;state.unlocked=ORDER.slice();CHARACTERS.forEach(c=>{if(!state.roster.includes(c.id))state.roster.push(c.id)});state.roster.push('hmurych');state.secret=true;log('ГУРИНТАЙМ','Хроника перешла в новую фазу.')}
checkAchievements();save();closeModal();renderAll();toast(choice.result);if(loc.id==='atlantis')setTimeout(()=>makeLogModal('ГУРИНТАЙМ · НОВАЯ ФАЗА','Парад продолжается','<p>'+safe(choice.result)+'</p><p>Теперь открыты все локации и архивные записи. В подвале снова 04:20. Так и должно быть.</p>',[{label:'Вернуться в экспедицию',primary:true,onClick:closeModal}]),500)}
function launchPysh(){if(smokeCooldown)return toast('ПЫЩ ПЕРЕЗАРЯЖАЕТСЯ. Костюк считает до четырёх.');smokeCooldown=true;const gain=state.smoke>=72?14:27;state.smoke=Math.min(100,state.smoke+gain);state.heat=Math.max(0,state.heat-12);state.puffs++;state.loops++;$('#smokeFx').innerHTML='';for(let i=0;i<15;i++){let puff=document.createElement('i');puff.className='smoke-cloud';puff.style.setProperty('--x',(Math.random()*100)+'vw');puff.style.setProperty('--y',(30+Math.random()*65)+'vh');puff.style.setProperty('--size',(70+Math.random()*190)+'px');puff.style.setProperty('--dur',(1.6+Math.random()*1.8)+'s');$('#smokeFx').appendChild(puff)}$('#smokeFx').classList.add('fire');const flash=document.createElement('div');flash.className='smoke-flash';document.body.appendChild(flash);setTimeout(()=>flash.remove(),400);const word=document.createElement('div');word.className='pysh-word';word.textContent='ПЫЩ!';document.body.appendChild(word);requestAnimationFrame(()=>word.classList.add('pop'));setTimeout(()=>word.remove(),1000);document.body.classList.add('glitch');setTimeout(()=>document.body.classList.remove('glitch'),450);setTimeout(()=>$('#smokeFx').classList.remove('fire'),2100);if(state.puffs===2)log('ЗАВУЧ','Кажется, где-то прозвучало «Геннадий Петрович…»');if(state.puffs>=3&&!state.secret){state.secret=true;if(!state.unlocked.includes('hmurych'))state.unlocked.push('hmurych');if(!state.roster.includes('hmurych'))state.roster.push('hmurych');log('СИГНАЛ 00:59','В дыму проступила дверь в параллельный подвал.');toast('ПЫЩ! СЕКРЕТНЫЙ МАРШРУТ ОТКРЫТ: ХМУРЫЧ')}else toast('ПЫЩ! ДЫМ +'+gain+' · ТРЕВОГА −12');if(navigator.vibrate)navigator.vibrate([30,45,70]);playTone(95,.11);checkAchievements();renderAll();save();$('#pyshButton').disabled=true;$('#heroPysh').disabled=true;$('#mobilePysh').disabled=true;setTimeout(()=>{$('#pyshButton').disabled=false;$('#heroPysh').disabled=false;$('#mobilePysh').disabled=false;smokeCooldown=false},1200)}
function playTone(freq,duration){if(!state.sound)return;try{const ctx=new(window.AudioContext||window.webkitAudioContext)(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='triangle';osc.frequency.value=freq;gain.gain.setValueAtTime(.045,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+duration);setTimeout(()=>ctx.close(),duration*1100)}catch{}}
function sideQuest(){state.oddity++;const lines=[['Глобус поворачивается сам. На обороте — наклейка «не поворачивать». Получено 7 GUR.',7,0],['Колумб выпадает из-за стенда. Он искал школьную столовую. +1 сникерс.',0,1],['Из глобуса выпадает билет в Атлантиду. Он просрочен на 59 лет, но принимается. +8 доверия.',0,0]];const e=lines[(state.oddity-1)%lines.length];state.gur=Math.min(999,state.gur+e[1]);state.snickers=Math.min(99,state.snickers+e[2]);if(state.oddity%3===0)state.trust=Math.min(100,state.trust+8);log('ПОБОЧНЫЙ ПРОТОКОЛ',e[0]);$('#oddityCard').classList.add('secret-reveal');setTimeout(()=>$('#oddityCard').classList.remove('secret-reveal'),2600);renderAll();toast(e[0]);playTone(430,.07)}

const CODEX=[
{id:'welcome',type:'СИСТЕМНЫЙ ФАЙЛ · 001',title:'Что такое 3115?',at:0,body:'3115 — не год. Это код доступа, частота и уровень гибкости реальности. Иногда — количество затяжек. Всегда — номер корпуса и пароль от подвала.\n\nЕсли слышишь «3115», значит, ты уже внутри сети. Если не слышишь — сеть пока делает вид, что тебя не замечает.',quote:'ПЫЩ-ПАРАД — это не история. Это состояние.'},
{id:'gurych',type:'ЛИЧНОЕ ДЕЛО · 059',title:'Геннадий Петрович Гурин',at:0,body:'Учитель истории. 59 лет, серый пиджак в мелу, треснутые очки и балаклава с биткоином. Левый валенок стоптан и потому считается боевым. Правый почти новый — парадный.\n\nОднажды учебник истории задымился у него в руках. С тех пор Наполеон танцует тверк, Колумб ищет сникерс, а Атлантида помещается в кармане.',quote:'«Ага...» — фраза, после которой история перестаёт быть прежней.'},
{id:'britven',type:'ЛИЧНОЕ ДЕЛО · 002',title:'Бритвень',at:0,body:'Лысый ёж в татуировках: портрет Гурыча, летящий валенок, «ПЫЩ» и «59». Молчит всегда. Одобряет кивком. Если кивнул — решение принято. Если смотрит — спорить уже поздно.\n\nПьёт «Кузбасское» из горла и помнит правила, которых никто не записывал.',quote:'Бритвень кивнул. Этого достаточно.'},
{id:'team',type:'СЕТЕВОЙ СПИСОК · 014',title:'Люди и сущности',at:1,body:'Костюк пишет биты, которые слышны в параллельной Атлантиде. Марк снимает легендарные хроники и создал Гуринголубя. Макс майнит GUR на трёх мониторах.\n\nСидоров ищет Колумба и падает как форма картографии. Егор доставляет экспедицию на Ниве. Рамм пытается всё посчитать, но калькулятор считает иначе.\n\nПыхтыч живёт в вентиляции. Склизкий Жиж предсказывает курс. ДымОхлюп знает дорогу сквозь туман. Картыч чертит маршруты на бумаге. Бигмук спит в Забытом подвале. Завуч остаётся в дыму. Хмурыч существует по понедельникам.',quote:'Пятый участник команды едет на крыше Нивы. Это не обсуждается.'},
{id:'map',type:'АТЛАС · ПОВРЕЖДЁННЫЙ',title:'Места силы',at:1,body:'Подвал школы №59 — сердце парада: сервер, бит, майнинг и первый дым. Вентиляция связывает все подвалы. На крыше Сидоров ищет Колумба, а Марк поднимает ретранслятор.\n\nЗабытый подвал находится за третьей дверью слева у бойлера. Подвал Рамм — место, где нет дыма и никто не хочет задерживаться. Атлантида всегда рядом со сникерсом.\n\nВход в подвал Хмурыча появляется только по понедельникам. Календарь утверждает, что сегодня не понедельник.',quote:'Если Картыч сказал «туда» — туда. Даже если там стена.'},
{id:'objects',type:'ИНВЕНТАРЬ · НЕ ВЫБРАСЫВАТЬ',title:'Артефакты',at:1,body:'Валенок — символ силы и способ проверить прочность глобуса. Гуринголубь переносит крипто-флешки сквозь нулевую видимость. Сникерс — микрофон, топливо, валюта и защита от скуки.\n\nКосяк знаний — учебник истории, скрученный в трубочку. Изолента чинит всё: от порванной страницы до разорванной причинности. Гуринкоин майнится под землёй и зависит от настроения Рамм.',quote:'1 сникерс = примерно 5 GUR. Или один кивок Бритвеня.'},
{id:'rituals',type:'ПРОТОКОЛ · 04:20',title:'Ритуалы подвала',at:2,body:'В 4:20 все собираются у сервера. Гурыч зажигает косяк знаний, Бритвень занимает угол, Марк включает запись, Костюк ловит бас. Рамм обещает посчитать длительность.\n\nПеред выходом положи сникерс в карман. Если валенок пойман — удача. Если не пойман — он вернётся. Возможно, не сразу и не тот.',quote:'Ритуал «Завуч в дыму»: напустить дыма. Дальше все делают вид, что план был такой.'},
{id:'prophecies',type:'ПРОРОЧЕСТВА · АУДИО НЕ ЧИТАТЬ',title:'Три предупреждения и одно курлыканье',at:3,body:'Бритвень: когда последний валенок упадёт в последний глобус, откроется Атлантида.\n\nЖиж: когда курс достигнет 59 000 GUR, все станут частью бочки.\n\nПыхтыч: если вентиляция забьётся дымом, все проснутся в Атлантиде.\n\nГуринголубь: если видео Марка наберёт 3115 триллионов просмотров, завуч снимет очки. Последняя часть записи — бас.',quote:'Пророчество не даёт точного времени. Кроме ритуала. Он в 4:20.'},
{id:'parallel',type:'НЕСАНКЦИОНИРОВАННЫЙ ФАЙЛ · 00:59',title:'Ветка Хмурыча',at:7,body:'Хмурыч — альтернативный Гурыч, который однажды не выпил пробирку в 00:59. Серый, тихий, вместо «ПЫЩ» говорит «пщ». Выходит только по понедельникам.\n\nОн знает, что Гурыч — это он, но в соседней ветке. Их подвалы разделяет одна дверь, две минуты и решение, которое так и не случилось.',quote:'Иногда закрытая дверь — просто незапущенная история.'},
{id:'achievements',type:'СЕРТИФИКАТЫ · НЕ ДЛЯ ПЕДСОВЕТА',title:'Отметки экспедиции',at:0,body:'У каждого подвала своя версия событий. Перепройди эпизоды, чтобы увидеть альтернативные решения. Собирай сигналы, находи тайные маршруты и не позволяй Рамм вести общий счёт.',quote:'Достижения сохраняются в локальной хронике.'}
];
function renderCodex(){let open=CODEX.filter(e=>e.at<=state.done.length||state.secret&&e.id==='parallel'||e.id==='achievements');$('#codexCounter').textContent=open.length+' / '+CODEX.length+' ФАЙЛОВ';$('#codexNav').innerHTML=CODEX.map(e=>{let can=open.includes(e);return '<button class="codex-link '+(can?'':'locked')+' '+(state.codex===e.id?'active':'')+'" data-codex="'+e.id+'">'+(can?'▸ '+safe(e.title):'▧ ФАЙЛ ЗАШИФРОВАН')+'</button>'}).join('');$$('[data-codex]').forEach(b=>b.onclick=()=>{const entry=CODEX.find(x=>x.id===b.dataset.codex);if(entry.at>state.done.length&&!(state.secret&&entry.id==='parallel'))return toast('АРХИВ ЗАШИФРОВАН. Продвинься по сюжету.');state.codex=entry.id;renderCodex()});let e=CODEX.find(x=>x.id===state.codex)||CODEX[0];$('#entryType').textContent=e.type;$('#entryTitle').textContent=e.title;$('#entryBody').innerHTML=e.body.split('\n\n').map(p=>'<p>'+safe(p)+'</p>').join('')+'<div class="quote">'+safe(e.quote)+'</div>';$('#entryUnlock').textContent='ДОСТУП: '+(e.at===0?'ОТКРЫТ':'СЮЖЕТ '+Math.min(e.at,6)+' / 6')+' · СИНХРОНИЗАЦИЯ ЛОКАЛЬНАЯ';$('#secretSubmit').onclick=checkSecret}
function renderInventory(){const cards=ARTIFACTS.map(a=>{let count=a.dynamic?state.snickers:a.id==='tape'?state.tape:a.id==='pigeon'?(state.done.includes('vent')?1:0):a.count;return '<article class="item-card '+(!count?'used':'')+'"><span class="item-icon">'+a.icon+'</span><b class="item-count">×'+count+'</b><h3>'+safe(a.name)+'</h3><p>'+safe(a.desc)+'</p></article>'}).join('');$('#inventoryGrid').innerHTML=cards;$('#inventoryCounter').textContent=(state.snickers+state.tape+3)+' ПРЕДМЕТА';$('#shopItems').innerHTML=[['snickers','Сникерс','запас от скуки и дверей',5],['tape','Изолента','чинит маршрут и мелкие парадоксы',8],['gur','Курс Макса','+12 GUR · комиссия в неизвестности',0]].map(x=>'<div class="shop-item"><span><b>'+x[1]+'</b><small>'+x[2]+'</small></span><button data-buy="'+x[0]+'">'+(x[0]==='gur'?'ОБМЕН':x[3]+' GUR')+'</button></div>').join('');$$('[data-buy]').forEach(b=>b.onclick=()=>buyItem(b.dataset.buy));$('#packSnickers').onclick=packSnickers}
function buyItem(id){if(id==='gur'){if(state.snickers<1)return toast('Нужен сникерс для обмена. Макс комиссию не отменяет.');state.snickers--;state.gur+=12;log('МАКС','Обменял один сникерс на 12 GUR. Жиж возражает.')}else{let cost=id==='snickers'?5:8;if(state.gur<cost)return toast('GUR не хватает. Попробуй принести Максу находку.');state.gur-=cost;if(id==='snickers')state.snickers++;else state.tape++;log('ЛАРЁК','Куплено: '+(id==='snickers'?'сникерс':'изолента')+'.')}renderAll();renderInventory();toast('ОБМЕН ПРОВЕДЁН. КВИТАНЦИЯ УЛЕТЕЛА ГОЛУБЕМ.')}
function packSnickers(){if(state.snickers<1)return toast('Сначала купи сникерс. Ритуал не принимает обещания.');if(state.gur<5)return toast('Нужно 5 GUR за карманную изоленту.');state.snickers--;state.gur-=5;state.trust=Math.min(100,state.trust+3);state.quests.snickers=true;log('РИТУАЛ','Сникерс уложен в карман. Скука отступила.');renderAll();renderInventory();toast('ЗАПАС НА МЕСТЕ. ВЫХОД РАЗРЕШЁН.')}
function checkSecret(){const value=$('#secretInput').value.trim().toUpperCase().replace(/[ .:]/g,'');if(['420','0420','3115','ПЫЩ','PYSH'].includes(value)){state.secret=true;if(!state.unlocked.includes('hmurych'))state.unlocked.push('hmurych');if(!state.roster.includes('hmurych'))state.roster.push('hmurych');state.codex='parallel';log('АРХИВ','Пароль принят. Открыта соседняя ветка 00:59.');checkAchievements();renderAll();renderCodex();toast('КОД ПРИНЯТ. ХМУРЫЧ НА ЛИНИИ.');$('#secretInput').value=''}else{secretSeen++;toast(secretSeen%3===0?'НЕ ТО. Подсказка: время сбора парада, без точки.':'ДОСТУП ОТКАЗАН. Завуч делает вид, что ничего не произошло.');$('#secretInput').select()}}

function renderAll(){renderResources();renderMap();renderSelected();renderJournal();if(state.view==='crew')renderCrew();if(state.view==='inventory')renderInventory();if(state.view==='codex')renderCodex();$('#crewCount').textContent=unlockedCharacters().length;$('#itemCount').textContent=state.snickers+state.tape+3;const cleared=state.done.length;$('#heroKicker').textContent=cleared?'ПРОТОКОЛ '+String(cleared+1).padStart(2,'0')+' · СВЯЗЬ УСТАНОВЛЕНА':'ПРОТОКОЛ 01 · ПОСЛЕ УРОКОВ';$('#heroTitle').innerHTML=cleared>=5?'ДОРОГА В <em>АТЛАНТИДУ</em>':cleared?'ЧАСТОТА <em>3115</em>':'ЧАСТОТА <em>3115</em>';$('#heroLead').textContent=cleared>=5?'Все узлы отвечают. Атлантида уже отражается в экране Макса, хотя монитор выключен. Осталось решить, какая версия истории станет следующей.':cleared?'Сигнал усилился. На карте появляются новые коридоры, в летописи — новые голоса. Система пытается вычислить источник дыма.':'Под полом школы №59 проснулся сервер. Гурыч зовёт на сбор: дым уже знает дорогу, а система пока думает, что это неисправность вентиляции.';$('#saveStatus').textContent='АВТОСОХРАНЕНИЕ';save()}
function switchView(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+view));$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.mobile-nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));state.view=view;if(view==='crew')renderCrew();if(view==='inventory')renderInventory();if(view==='codex')renderCodex();save();window.scrollTo({top:0,behavior:'smooth'})}
function mapHint(){const hints=['КАРТЫЧ: Тут была стена. Потом мы передумали.','МАРК: Камера видит ещё один узел. Камера сейчас выключена.','РАММ: Расстояние до Атлантиды — 3,7 валенка.','БРИТВЕНЬ: (смотрит на север, который внизу)','СИСТЕМА: Несоответствие карты реальности. Продолжайте.'];const text=hints[Math.floor(Math.random()*hints.length)];$('#mapToast').textContent=text;$('#mapToast').classList.add('show');setTimeout(()=>$('#mapToast').classList.remove('show'),2700);if(++oddityQuotes%5===0){state.gur+=3;toast('Картыч нашёл 3 GUR в сгибе карты.');save();renderResources()}}
function renderCodex(){let open=CODEX.filter(e=>e.at<=state.done.length||state.secret&&e.id==='parallel'||e.id==='achievements');$('#codexCounter').textContent=open.length+' / '+CODEX.length+' ФАЙЛОВ';$('#codexNav').innerHTML=CODEX.map(e=>{let can=open.includes(e);return '<button class="codex-link '+(can?'':'locked')+' '+(state.codex===e.id?'active':'')+'" data-codex="'+e.id+'">'+(can?'▸ '+safe(e.title):'▧ ФАЙЛ ЗАШИФРОВАН')+'</button>'}).join('');$$('[data-codex]').forEach(b=>b.onclick=()=>{const entry=CODEX.find(x=>x.id===b.dataset.codex);if(entry.at>state.done.length&&!(state.secret&&entry.id==='parallel'))return toast('АРХИВ ЗАШИФРОВАН. Продвинься по сюжету.');state.codex=entry.id;renderCodex()});let e=CODEX.find(x=>x.id===state.codex)||CODEX[0];$('#entryType').textContent=e.type;$('#entryTitle').textContent=e.title;$('#entryBody').innerHTML=e.body.split('\n\n').map(p=>'<p>'+safe(p)+'</p>').join('')+'<div class="quote">'+safe(e.quote)+'</div>';$('#entryUnlock').textContent='ДОСТУП: '+(e.at===0?'ОТКРЫТ':'СЮЖЕТ '+Math.min(e.at,6)+' / 6')+' · СИНХРОНИЗАЦИЯ ЛОКАЛЬНАЯ';$('#secretSubmit').onclick=checkSecret}
function renderInventory(){const cards=ARTIFACTS.map(a=>{let count=a.dynamic?state.snickers:a.id==='tape'?state.tape:a.id==='pigeon'?(state.done.includes('vent')?1:0):a.count;return '<article class="item-card '+(!count?'used':'')+'"><span class="item-icon">'+a.icon+'</span><b class="item-count">×'+count+'</b><h3>'+safe(a.name)+'</h3><p>'+safe(a.desc)+'</p></article>'}).join('');$('#inventoryGrid').innerHTML=cards;$('#inventoryCounter').textContent=(state.snickers+state.tape+3)+' ПРЕДМЕТА';$('#shopItems').innerHTML=[['snickers','Сникерс','запас от скуки и дверей',5],['tape','Изолента','чинит маршрут и мелкие парадоксы',8],['gur','Курс Макса','+12 GUR · комиссия в неизвестности',0]].map(x=>'<div class="shop-item"><span><b>'+x[1]+'</b><small>'+x[2]+'</small></span><button data-buy="'+x[0]+'">'+(x[0]==='gur'?'ОБМЕН':x[3]+' GUR')+'</button></div>').join('');$$('[data-buy]').forEach(b=>b.onclick=()=>buyItem(b.dataset.buy));$('#packSnickers').onclick=packSnickers}
function openHelp(){makeLogModal('СПРАВОЧНИК · ЗАКРЫТАЯ СЕТЬ','Инструкция из подвала','<p><b>Карта:</b> выбирай открытые узлы. Прохождение главы открывает следующий маршрут и новые записи архива.</p><p><b>Решения:</b> каждое меняет GUR, сникерсы, доверие, дым или внимание системы. Некоторые требуют ресурс.</p><p><b>ПЫЩ:</b> увеличивает плотность дыма и снижает внимание системы. Трижды нажми кнопку, чтобы найти ветку Хмурыча. Кнопка работает также с клавишей «П».</p><p><b>Команда:</b> в поле выходят до четырёх героев. Костюк помогает с ритмом, Картыч с маршрутами, Пыхтыч в вентиляции, Марк на крыше, Бритвень в Забытом подвале, Рамм у себя.</p><p><b>Карман:</b> покупай запасы у Макса. Подсказка к секретному паролю спрятана в архиве.</p><p>В игре нет стрельбы и прыжков по платформам: экспедиция держится на историях, маршрутах, ресурсах и решениях.</p>',[{label:'ПРИНЯТО',primary:true,onClick:closeModal}])}
function openOddity(){const rewards=['глобус показал дверь, которой не было','с полюса выпал старый сникерс','на карте проявилась точка «тут уже были»','Колумб оставил записку: «ушёл за шоколадкой»','Бритвень кивнул глобусу. Теперь тот крутится сам'];state.oddity++;let i=state.oddity%rewards.length;state.gur=Math.min(999,state.gur+5);if(state.oddity%2===0)state.trust=Math.min(100,state.trust+2);log('ПОБОЧНЫЙ ПРОТОКОЛ',rewards[i]+'. +5 GUR');renderAll();makeLogModal('ПОБОЧНЫЙ ПРОТОКОЛ · '+String(state.oddity).padStart(2,'0'),'Глобус смотрит на тебя','<p>Ты поворачиваешь глобус. Земля делает вид, что так и планировала: '+safe(rewards[i])+'.</p><div class="dialogue">НАГРАДА: +5 GUR'+(state.oddity%2===0?' · +2 доверия':'')+'<br>ПРИМЕЧАНИЕ: Рамм записала долготу как «примерно туда».</div>',[{label:'ЕЩЁ ОДИН СЕКРЕТ?',onClick:()=>{closeModal();if(state.oddity%3===0)launchPysh()}},{label:'ЗАБРАТЬ НАХОДКУ',primary:true,onClick:closeModal}])}
function exportChronicle(){const blob=new Blob([JSON.stringify({game:'PYSH-3115',version:4,state:state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='3115-chronicle.json';a.click();URL.revokeObjectURL(url);toast('ХРОНИКА ВЫГРУЖЕНА. Голубь доставит файл.') }
function resetGame(){makeLogModal('СИСТЕМНАЯ КОМАНДА','Сбросить хронику?','<p>Локальное сохранение этой игры будет очищено. Экспортируй летопись заранее, если хочешь оставить её себе.</p>',[{label:'ОТМЕНА',onClick:closeModal},{label:'СБРОСИТЬ',primary:true,onClick:()=>{localStorage.removeItem(SAVE_KEY);state=freshState();selected='basement';closeModal();renderAll();toast('Подвал снова в 04:20. Ага...')}}])}
function bind(){ $$('.tab,.mobile-nav [data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#pyshButton').onclick=launchPysh;$('#heroPysh').onclick=launchPysh;$('#mobilePysh').onclick=launchPysh;$('#heroContinue').onclick=()=>{document.querySelector('.map-panel').scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>startMission(activeLocation()),240)};$('#helpBtn').onclick=openHelp;$('#launchMission').onclick=()=>startMission(activeLocation());$('#mapHint').onclick=mapHint;$('#oddityBtn').onclick=openOddity;$('#exportSave').onclick=exportChronicle;$('#oddityCard').onclick=e=>{if(e.target.closest('button'))return;openOddity()};$('#soundToggle').onclick=()=>{state.sound=!state.sound;$('#soundToggle').style.color=state.sound?'var(--acid)':'';toast(state.sound?'ТЕРМИНАЛЬНЫЙ ЗВУК ВКЛЮЧЁН':'ЗВУК ВЫКЛЮЧЕН');playTone(420,.08);save()};$('#modalClose').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop'))closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if((e.key==='p'||e.key==='P'||e.key==='з'||e.key==='З')&&!/INPUT|TEXTAREA/.test(document.activeElement.tagName))launchPysh()});$('#heroPysh').title='ПЫЩ! или нажми П';$('#reset').onclick=resetGame}
function startClock(){let seconds=0;setInterval(()=>{seconds++;let total=20+seconds,mm=4+Math.floor(total/60),ss=total%60;$('#clock').textContent=String(mm).padStart(2,'0')+':'+String(ss).padStart(2,'0')+':00';$('#chapterTime').textContent=String(mm).padStart(2,'0')+':'+String(ss).padStart(2,'0')},1000)}
function boot(){if(!state.roster)state.roster=['gurych','britven','kostyuk'];if(state.secret&&!state.roster.includes('hmurych'))state.roster.push('hmurych');if(state.sound)$('#soundToggle').style.color='var(--acid)';bind();renderAll();startClock();if(!state.seenIntro){state.seenIntro=true;save();setTimeout(()=>toast('ЧАСТОТА 3115 ОБНАРУЖЕНА. Нажми ПЫЩ, чтобы начать с шума.'),700)}}
boot();
